---
title: "Does flipper length predict body mass in Palmer penguins?"
author: "Irena Papst"
format: revealjs
editor: visual
---

```{r}
#| label: setup
#| echo: false
#| message: false
library(palmerpenguins)
library(dplyr)
library(ggplot2)
```

## Analysis code

```{r}
#| label: fun_get_model_coef
get_model_coef = function(species_name){
  obs = (penguins 
    |> dplyr::filter(species == species_name)
  )
    
  model_coef = (
    lm(body_mass_g ~ flipper_length_mm, data = obs)
    |> coefficients()
  )
  
  return(list(
    obs = obs, 
    model_coef = model_coef
  ))
}
```

---

```{r}
#| label: fun_make_model_plot
#| echo: false
make_model_plot = function(species_name){
  plot_data = get_model_coef(species_name)
  
  pp = (ggplot(plot_data$obs)
    + geom_point(
      aes(x = flipper_length_mm,
          y = body_mass_g),
      shape = 1, size = 4, stroke = 1.5, alpha = 0.5
      )
    + geom_abline(intercept = plot_data$model_coef[1], 
                  slope = plot_data$model_coef[2],
                  linewidth = 2, colour = "dodgerblue", alpha = 0.7)
    + labs(
      x = "Flipper length (mm)",
      y = "Body mass (g)",
      title = paste("Relationship between flipper length and body mass for",
                    species_name,
                    "penguins"),
      subtitle = "Observations (points) vs linear model fit (line)"
    )
    + theme_bw(
      base_size = 16
    )
  )
  
  return(pp)
}
```

```{r}
#| label: plot_adelie
#| echo: false
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
make_model_plot("Adelie")
```

---

```{r}
#| label: plot_chinstrap
#| echo: false
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
make_model_plot("Chinstrap")
```
